app = 'zedia'
primary_region = 'sea'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  protocol = 'tcp'
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false # prevent automatic suspension
  min_machines_running = 1 # keep a machine running at all times

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
